### ISSUE TITLE
TOFU

### ISSUE THREAD

**Issue by snoe** [snoe/deedum#10]
store host and port

**Comment by snoe** [comment]
Fixed by 2cd9fd99e6e60c8cd2bca6a1e63c98ed8b1f4aa6

**Comment by makeworld-the-better-one** [comment]
I'm happy to see TOFU support in deedum! If I can make a suggestion: Store the hash of the SubjectPublicKeyInfo part of the cert, and not the hash of the entire cert. This idea comes from [this report](https://rp.delaat.net/2012-2013/p56/report.pdf) which Solderpunk shared on the mailing list a little while ago, in the "Thoughts on TOFU" thread. The SPKI portion of the cert changes less often, so there will be less false positives of TOFU errors.
