### ISSUE TITLE
Handle unordered list line type

### ISSUE THREAD

**Issue by jfmcbrayer** [snoe/deedum#11]
Currently, it's just left as '*'. It would be nice to indent, and replace with a Unicode bullet or some other nice wingding like ❧.

**Comment by makeworld-the-better-one** [comment]
I would suggest `•`, U+2022. Maybe something larger though, you can find a list of bullet style characters [here](https://stackoverflow.com/questions/12971187/what-would-be-the-unicode-character-for-big-bullet-in-the-middle-of-the-characte).

**Comment by idc-snoe** [comment]
Fixed by 260e7a64cc8d13297b80fa79da38e75f01ac6dab

**Comment by snoe** [comment]
fixed by 172329
