### ISSUE TITLE
feature request: submit to fdroid?

### ISSUE THREAD

**Issue by linuxclowns** [snoe/deedum#14]
Would be great to see a non play store version of this app available.

**Comment by guzzisti** [comment]
for the record: Deedum is available on IzzyOnDroids Repo
https://apt.izzysoft.de/fdroid/index/apk/ca.snoe.deedum

**Comment by snoe** [comment]
deedum is now available on the main fdroid repo!
https://f-droid.org/en/packages/ca.snoe.deedum/

**Comment by IzzySoft** [comment]
@snoe now that Deedum is available at F-Droid.org directly: shall I still keep it in mine? I usually remove apps after an overlap of about a week or a little more once they made it into "F-Droid proper" – unless explicitly being asked to keep them (you can find [some background here](https://gitlab.com/IzzyOnDroid/repo/-/wikis/FAQ)).

**Comment by snoe** [comment]
@IzzySoft I think you can remove it, thank you for your help.

**Comment by IzzySoft** [comment]
Allright, thanks @snoe! Should you need it back for any reason at any point, just let me know.
