### ISSUE TITLE
Suggestions for content typeface

### ISSUE THREAD

**Issue by ivan-avalos** [snoe/deedum#16]
Hello! I think Merriweather is fine, but I don't find it very comfortable for long text, and the glyphs are weird. I would like to suggest some open source serif and sans-serif typefaces that I think would look better:

## Serif
* Noto Serif.
* Source Serif Pro.
* IBM Plex Serif.

## Sans-serif
* Open Sans.
* Roboto.
* Source Sans Pro.
* IBM Plex Sans.
* Lato.

Or maybe we can use a semi-bold sans-serif for headings and a serif for text and links. And maybe we can add a setting to switch between sans and sans-serif for headings and text. I can work on the pull request, I just wanted to ask for your opinion and others'.

**Comment by snoe** [comment]
Thanks for this, I'm pretty bad at design so I'm happy to take any informed approach here. I probably just copied a site that I thought was easy to read.

Long term, I would like the user to have control over this since it is so subjective.

I'm happy to take a PR for which font you like best.

**Comment by ivan-avalos** [comment]
#17
