### ISSUE TITLE
Internal exception when navigating to any sites

### ISSUE THREAD

**Issue by prcmt** [snoe/deedum#19]
Installed app this morning, got an error immediately when loading default page. :)

Tried a couple other Gemini sites with no change.

```
An error occurred

INTERNAL EXCEPTION
```

![IMG_20200901_101535](https://user-images.githubusercontent.com/59378788/91831806-6bdc1600-ec3c-11ea-81f9-ebc1e715e659.jpg)

* deedum 2020.0831.1503
* Android 10

**Comment by makeworld-the-better-one** [comment]
I am not experiencing this, sounds like it could be a network issue on your part. I am also on Android 10 with the same version of Deedum.

**Comment by snoe** [comment]
I'm also not experiencing that.
If host lookup was failing though, I'd expect to see an `Failed host lookup: 'gemini.circumlunar.space'` So either DNS is caching or maybe traffic on 1965 is being blocked/modified.

**Comment by prcmt** [comment]
Yup, outbound traffic on 1965 was being blocked on my network. Thanks!

**Comment by makeworld-the-better-one** [comment]
@snoe It'd be helpful if the error text was displayed as well, it would be debugging these issues a lot easier.
