### ISSUE TITLE
Submit to App Store

### ISSUE THREAD

**Issue by ivan-avalos** [snoe/deedum#20]
Hello! I was just wondering: do you think you'll be able to publish this to the App Store? If not, I have an Apple Developer membership, I could take care of that if you want. I'd be glad to do it! :)

**Comment by snoe** [comment]
@ivan-avalos (sorry I've been afk)

That would be fantastic if you could publish it actually. I haven't touched ios for a decade so if you know how to navigate it, please do.

**Comment by ivan-avalos** [comment]
Do I need to do write configuration for Fastlane? Maybe I can just manually publish new releases to the App Store.

**Comment by snoe** [comment]
No idea. I'm just manually publishing to google, but if the pace of releases picks up I'll have to find something automatic.

**Comment by ivan-avalos** [comment]
I wonder if not using WKWebView might be a problem for App Store review. We're building our own rendering engine based on Flutter components, not sure if the Apple restriction only applies for Web browsers.

**Comment by ivan-avalos** [comment]
According to [App Store Review Guidelines](https://developer.apple.com/app-store/review/guidelines/), there is no problem:
> 2.5.6 Apps that browse the web must use the appropriate WebKit framework and WebKit Javascript.

**Comment by ivan-avalos** [comment]
@snoe The app has been submitted for review!

**Comment by snoe** [comment]
woohoo! thank you.

**Comment by pitr** [comment]
is there a link to testflight?

**Comment by ivan-avalos** [comment]
@pitr I submitted the app directly to the App Store, it won't be available on TestFlight.

**Comment by ivan-avalos** [comment]
The app was rejected because the reviewer searched "sex" in GUS, and found minor sex references, so I had to adjust the age rating. Let's hope it is accepted this time.

**Comment by pitr** [comment]
You need to toggle "17+" and unrestricted web access (I believe one enables the other). That's what I did with [The Gemini Browser](https://github.com/pitr/gemini-ios) ([app store link](https://apps.apple.com/app/id1514950389)).

Also, my suggestion is to clarify to reviewer AND in app description that this is not a browser for web. People don't understand what "protocol" is and assume that any browser is for web. This resolved the rejection I got. Good luck!

**Comment by ivan-avalos** [comment]
@pitr Thanks for the tips! I just toggled "Unrestricted web access", turning my 12+ rating into 17+. Hopefully this will make it more likely to be accepted.

**Comment by ivan-avalos** [comment]
Rejected again, this time because I forgot to remove the "Debug" label in some screenshots. It will take me a long time to take those screenshots again, my computer sucks.

**Comment by ivan-avalos** [comment]
Great news! deedum was finally accepted in the App Store! It took some negotiating, but it's finally available! https://apps.apple.com/app/deedum/id1546810946

**Comment by snoe** [comment]
Thanks for persevering through this @ivan-avalos!
