### ISSUE TITLE
Typography recommendations for bulletted lists

### ISSUE THREAD

**Issue by ddevault** [snoe/deedum#23]
The bulletted lists would look nicer if, when bullets are found on a page, a horizontal margin is added to paragraphs and headings, and this new left margin is used to display a Unicode bullet point character (•) instead of an asterisk (*).

It would look something like this:

![](https://l.sr.ht/zt6a.png)

**Comment by makeworld-the-better-one** [comment]
️

**Comment by snoe** [comment]
Thanks! Fixed by aad05de3dca269643b496a6b9283dfb99c4ee897

I decided to indent the bulleted paragraph, otherwise lines right after were not possible to distinguish as part of the bullet.
