### ISSUE TITLE
Feature request: View page source

### ISSUE THREAD

**Issue by pixdrift** [snoe/deedum#27]
I am not sure if deedum currently supports this, I have primarily been testing on Android, but the ability to 'view page source' or 'switch to source view' at a gemini URL would be handy.

I am interested to see what others are creating in gemini and how the pages are assembled, this would provide a quick way to pull the pages apart. It may also be useful for troubleshooting page rendering etc. for developers.

**Comment by karmanyaahm** [comment]
I can try implementing this. Though I'm unsure of whether it would be better to have wrapped lines or to have a preformatted block?

**Comment by snoe** [comment]
@karmanyaahm 
This makes sense. As a heads up, one of the things I would like (eventually) to do is present the parent/root/next/prev functionality laid out by the posts below. I'm imagining a second bar placed below the address bar, either shown with a toggle button next to the address bar, a setting, or placed above content that you scroll up to. If you can keep that in mind it might inform what's done with this card.

Here's how the mozz.us proxy shows it.
<img width="380" alt="Screen Shot 2021-01-27 at 9 13 03 AM" src="https://user-images.githubusercontent.com/105012/106021489-176d8300-6082-11eb-9eaf-8fb129d87ad5.png">

gemini://mozz.us/journal/2021-01-01.gmi
https://portal.mozz.us/gemini/mozz.us/journal/2021-01-01.gmi
gemini://gemini.circumlunar.space:1965/~solderpunk/gemlog/gemini-client-navigation.gmi
https://portal.mozz.us/gemini/gemini.circumlunar.space:1965/~solderpunk/gemlog/gemini-client-navigation.gmi

**Comment by karmanyaahm** [comment]
As for the second bar, I'm not sure if you want it visible at all times, but maybe something like the five icons Firefox implements in the popup menu would work?

![Screenshot_20210218-011657](https://user-images.githubusercontent.com/32671690/108314045-45c51680-7187-11eb-9b1a-be087e5f05ab.png)
