### ISSUE TITLE
Open Link in New Tab

### ISSUE THREAD

**Issue by karmanyaahm** [snoe/deedum#32]
It would be nice if it was possible to have the option to open links in a new tab when long pressing. I'll see if I can get something working and submit a PR.

**Comment by karmanyaahm** [comment]
@snoe (and everyone who uses deedum) would a context menu like thing like in the first image or what Firefox does like in the second image be better?
![Screenshot_20201230-013429](https://user-images.githubusercontent.com/32671690/103334588-f93f4380-4a3f-11eb-8374-129485350236.png)
![Screenshot_20201230-013514](https://user-images.githubusercontent.com/32671690/103334592-ff352480-4a3f-11eb-8dbd-ed113ba5ccf8.png)

**Comment by snoe** [comment]
Nice, thank you. I have no preference, but would want to make sure copy link is an option if the long press to copy is replaced by this.

**Comment by contrapunctus-1** [comment]
I'd request a menu which is close to the bottom, for easy one handed use. (And even for easier two handed use, since bottom oriented UIs require less movement of the hands.)
