### ISSUE TITLE
IDN support

### ISSUE THREAD

**Issue by MCMic** [snoe/deedum#34]
Attempt to load gemini://français.lanterne.chilliet.eu fails.

It's percent-encoding instead of punycoding the domain.

**Comment by karmanyaahm** [comment]
I'm not sure what the progress on this issue has been but i tried the follow *Dart* (not Flutter) program
```dart
import 'dart:io';
void main(){
 RawSecureSocket.connect("français.lanterne.chilliet.eu", 1965, timeout: Duration(seconds: 5));
}
```
And it throws an exception. The percent encoding can be easily eliminated in Flutter but this seems to be the bigger problem. I'll try looking for some way to IDN convert this.

**Comment by karmanyaahm** [comment]
It seems like the punycode library has a few prerequisites
https://github.com/close2/punycode/issues/1
Of the two prerequisites, rfc3454 seems to have a dart library, but I'm not sure if rfc7564 has one, and it looks too complicated to implement directly in the app.

Any advice?

**Comment by karmanyaahm** [comment]
I found a solution I'll send a PR soon 

<https://github.com/Teifun2/nextcloud-cookbook-flutter/blob/542425b77e9dbc65207c4f02ab832239dcd31a62/lib/src/screens/form/login_form.dart#L225>

**Comment by karmanyaahm** [comment]
@snoe this issue can now be closed
