### ISSUE TITLE
Tab number not updating

### ISSUE THREAD

**Issue by karmanyaahm** [snoe/deedum#35]
When I open a new tab, the number in the 'open tabs menu' box near the address bar stays the same. In most browsers, that shows the number of tabs, so I'm assuming this is a bug and not intended? The number is shown here.
<https://github.com/snoe/deedum/blob/9c2e96d0ef91d566dea3088f7a825cd3d3bf7545/lib/browser_tab.dart#L405-L416>
I tested some older versions from git and this bug seems to have been there for a while.

I think this might be because IndexedStack preserves the state of the widgets inside it and doesn't re-render them whenever they're displayed. One solution to this might be displaying the address bar and content separately, but that would require updating a lot of the display logic, so I'm not sure what the right solution here is.

**Comment by snoe** [comment]
Yeah, I think tabs have some problems. I suspect getting the `appKey.currentState.tabs.length` is skipping `setState` of browsertab state so nothing rerenders. If the tabs was passed into the browsertab constructor it should do it.

**Comment by snoe** [comment]
Looked at this for a bit more, `IndexedStack` simply doesn't rerender hidden children. I played a bit with changing all the `tab['key']` values when tabs changed but that led to other problems in the `Tab` list. Even if we move the stack to the content, I suspect we'll have the problem between `Directory` and `BrowserTab`.

This suggests `TabBarView` might work https://stackoverflow.com/a/58535348 

This uses `IndexedStack` and could probably be learned from: https://medium.com/flutter-community/creating-a-full-featured-browser-using-webviews-in-flutter-9c8f2923c574 

I wish flutter had more clear examples of full app layout.

**Comment by snoe** [comment]
This should be fixed with 136be837f73a6a9665cd9845a88e20fc713f0c2a
