### ISSUE TITLE
Timeout too short?

### ISSUE THREAD

**Issue by guzzisti** [snoe/deedum#39]
I have sometimes issues opening gemini capsules in Deedum which open fine in other clients.
Deedum shows me a red page:
```
An error occured

No response. timeout
```

This happens mostly on sites that need a second or two to respond, i.e. for creating dynamic content. What is the current timeout value and can this be made a setting?

**Comment by ivan-avalos** [comment]
This has already been fixed in #38.

**Comment by guzzisti** [comment]
A, i missed that one, was looking for other issues but not for PRs.

Thanks to @snoe and you for creating and improving deedum.

**Comment by ivan-avalos** [comment]
@snoe This issue can be closed.
