### ISSUE TITLE
Feature Request: theming

### ISSUE THREAD

**Issue by mister-monster** [snoe/deedum#42]
It would be nice to be able to pick colors for rendering and change the bar color. A black theme would be nice. At the very least, an option to render pages with black background and white text would be great.

**Comment by snoe** [comment]
Absolutely. I actually want to eventually support per-url theming. 

I think https://github.com/snoe/deedum/pull/21 was a step to allowing configurable fonts if anyone wants to pick it up or use it as inspiration for another go.

A PR around custom colors would be welcome too. It will need to consider night-mode.

**Comment by snoe** [comment]
I think I'm going to close this and leave deedum just with darkmode.
