### ISSUE TITLE
Show images progressively

### ISSUE THREAD

**Issue by lenzj** [snoe/deedum#43]
I was browsing the site below using deedum on android and when I click on any of the links to images (pok3r, tg4x, gergoplex), deedum opens a blank page and won't display the image?  Interestingly if I press the Android home button and then switch back to deedum it displays just the top 10% of the image?

gemini://rawtext.club/~ecliptik/keyboards.gmi

A few alternative clients have been tried (Ariene, Lagrange, bombadillo) and they seem to be able to open the images fine on the above gemini site.

**Comment by lenzj** [comment]
After further evaluation Ariene sometimes has an error with the site above as well.  Sometimes Ariene opens the picture fine and sometimes it responds with "Permanent Failure:...".  I'm guessing maybe the gemini server on the site may be only delivering partial images sometimes.

I'll leave this open for a few days to see if anyone else has thoughts/comments and then I'll close.

**Comment by snoe** [comment]
Beyond misbehaving servers, it would be nice to display images progressively.

**Comment by cloudrac3r** [comment]
> After further evaluation Ariene sometimes has an error with the site above as well. Sometimes Ariene opens the picture fine and sometimes it responds with "Permanent Failure:...".

This is almost certainly an Ariane bug. Ariane is very buggy, particularly with regards to URL handling. It should not be used as a reference.

**Comment by snoe** [comment]
This should be fixed in deedum, I reworked some of this during the new year, and images were handling re-rendering very poorly. The page in question seems to work much better now.
