### ISSUE TITLE
unable to open gemini URLs with nonstandard ports without gemini scheme in url

### ISSUE THREAD

**Issue by splatt9990** [snoe/deedum#45]
If you enter a gemini URL sans the Gemini scheme portion and a nonstandard port (i.e. not 1965) deedum thinks the URL is not a Gemini URL and complains it doesn't have an app to open the link. 

This is an issue mainly because deedum strips the scheme off the URL on navigating to it, making a typo annoying to fix.

To clarify, with the full scheme in the URL, deedum is capable of fetching the page even with a nonstandard port.

OS: Android 10
Deedum version: 2021.0130.2032 (Play store)

**Comment by snoe** [comment]
> This is an issue mainly because deedum strips the scheme off the URL on navigating to it, making a typo annoying to fix.

This no longer happens, I looked into accepting something like `127.0.0.1:1234` as gemini but I couldn't figure out a good way to do so while keeping the search working. So, unless someone comes up with a PR I'll leave it here.
