### ISSUE TITLE
Feature request: bigger text

### ISSUE THREAD

**Issue by ssb22** [snoe/deedum#47]
My eyesight is bad, I would like an option for all text to be larger (like the "Text Scaling" option in Chrome's Accessibility settings).  Thanks for all your work on this.

**Comment by snoe** [comment]
@ssb22 
For normal text, a setting to adjust the default size sounds pretty straightforward.

Next, a sort of text scaling exists for fixed-width blocks you can double click a block and override the fit-to-width default, would you like a larger scale there say 24 or 16 chars per line or is the existing 32 char per line readable? 

I'm inclined to keep the double click to zoom in behaviour for fixed-width over a setting to keep it at a low char per line. Most fixed-width content was built with a column width in mind so overriding that would probably make a lot of ascii art and even plain text have weird line-wrap + page break behaviour. Does that sound ok to you or would you prefer a setting for locking fixed-width into a char per line mode?

**Comment by farvardin** [comment]
I agree, text is way too small (and in serif it looks even smaller), it should at least follow the default user settings in the android  display configuration.

**Comment by snoe** [comment]
Fixed by e109892 it should now follow os accessibility font sizing.

**Comment by farvardin** [comment]
Thanks a lot @snoe , it's perfect this way. I got the new version on fdroid this morning!

**Comment by ssb22** [comment]
This has now arrived on Google Play updates as well.  Many thanks.
