### ISSUE TITLE
Screenshots?

### ISSUE THREAD

**Issue by koyuawsmbrtn** [snoe/deedum#48]
It'd be nice to have a look at the app before downloading APKs from the internet. Would make it a lot more trustworthy.

**Comment by licaon-kter** [comment]
/close as invalid

Screenshots are shown on F-Droid (client and web): https://github.com/snoe/deedum/blob/master/fastlane/metadata/android/en-US/images/phoneScreenshots/1.png

**Comment by sario528** [comment]
Screenshots also available on Google Play listing https://play.google.com/store/apps/details?id=ca.snoe.deedum&hl=en_US&gl=US
