### ISSUE TITLE
code in a block is too big

### ISSUE THREAD

**Issue by eggplants** [snoe/deedum#49]
When browsing [my site](gemini://eggplants.srht.site/cheatsheet.gmi) with deedum:

![Screenshot_20210921-225238](https://user-images.githubusercontent.com/42153744/134188335-b259daa9-84ce-43d1-97b5-49173d5a8a35.png)

**Comment by snoe** [comment]
this behaviour is nice for ascii art but for a lot of text like this, it should probably wrap. 

the app should allow users to store per site or domain preferences like font-size, colors, and fixed width font handling.

**Comment by snoe** [comment]
Added a change in 9c97f30 to pad lines to a minimum of 32 by default. This makes examples, like these, look much better.

**Comment by eggplants** [comment]
𝑻𝒉𝒂𝒏𝒌 𝒚𝒐𝒖...
