### ISSUE TITLE
modalBarrierDismissLabel called on null

### ISSUE THREAD

**Issue by ssb22** [snoe/deedum#54]
Hi, I'm on deedum version 2021.0221.1640 from Play Store, I tried to open gemini://gemini.ctrl-c.club/ and got:

    An error occurred
    NoSuchMethodError: The getter 'modalBarrierDismissLabel' was called on null.
    Receiver: null
    Tried calling: modalBarrierDismissLabel

I think ctrl-c.club might have changed their host key, so it's possible that deedum is trying to pop up a "host key changed" warning but the code that does that has a null-pointer bug.  Other hosts don't seem to be affected.

**Comment by snoe** [comment]
I was running into this as well, and when I went looking to reproduce it I believe @areille fixed it in https://github.com/snoe/deedum/pull/53. After installing the new release, it properly pops up the host key warning. The new release should be in the play store soon.
