### ISSUE TITLE
Grey screen on tabs list

### ISSUE THREAD

**Issue by DanielChesters** [snoe/deedum#56]
When I go on the tabs list, I have a grey screen with nothing since the last update (2021.1203.0440).

![Screenshot_20211207-133828](https://user-images.githubusercontent.com/291102/145030868-c1ef367b-8e0f-48b2-815f-ad5c140f6be7.jpg)

I use an OnePlus Nord (AC2003), Android 11, and Oxygen OS 11.6.6.AC01BA

**Comment by DanielChesters** [comment]
I can "fix" the issue by delete local data.

**Comment by DanielChesters** [comment]
I just reproduce the issue with only a tab selection (the tab goes grey like the screenshot and does not seems to go in their normal state)

**Comment by snoe** [comment]
I'm having trouble reproducing this, I'm not sure exactly what you meant by "with only a tab selection".

Starting from deleted local data, what steps do you take to get into this state?

**Comment by DanielChesters** [comment]
Hi,

Sorry if I am not enough clear. If I remember correctly, the grey list tab reappears "randomly" when I select a tab on the tab list and the tab list works fine for a while before that. Sorry if I don't have more information for the moment.

-------- Original Message --------

**Comment by snoe** [comment]
@DanielChesters Can you let me know if this is happening on the latest version? I did see it once on the previous version but was unable to reproduce it, and haven't seen it since on version 2021.1215.0738+19.

**Comment by DanielChesters** [comment]
Hello,

Since I had Version 2021.1215.0738 on my phone, this issue seems to be fixed.

Thanks you. 👍

-------- Original Message --------
