### ISSUE TITLE
https links not opening

### ISSUE THREAD

**Issue by scompo** [snoe/deedum#57]
Hi, after installing the latest fdroid version (2021.1203.0440) https links are not opened in the browser.

The program tells me it can't find an app to open the link.

**Comment by Conky5** [comment]
I am encountering this error as well.

**Comment by snoe** [comment]
Fixed by 39fbda2 (I hope)

I think this was caused https://developer.android.com/training/basics/intents/package-visibility although I'm compiling to api 28, it could be required by your phone's android version.

**Comment by scompo** [comment]
I can confirm it works fine now, thank you for the quick fix, have a nice holiday!
