### ISSUE TITLE
Can change settings values (virtual keyboard close instantly)

### ISSUE THREAD

**Issue by DanielChesters** [snoe/deedum#58]
Hi, after I remove all my local data to "fix" my tabs grey list issue, I found another issue when I try to change the homepage setting (or the search engine URI). The virtual keyboard open when I select a field on settings page and close instantly.

I have a OnePlus Nord (AC2003) with Oxygen OS 11.6.6.AC01BA (Android 11) and the last version of the application.

**Comment by snoe** [comment]
I'm able to reproduce this. Until I get a fix out you can tap the input until the keyboard stays open to get around it.
