### ISSUE TITLE
Selecting text frustratingly scrolls page

### ISSUE THREAD

**Issue by DocSunset** [snoe/deedum#61]
My spouse found that if they rest their thumb on the page (e.g. moving it slightly, trying to keep the screen from sleeping while reading a long article), if they accidentally trigger text selection, the page would scroll to a position several paragraphs earlier in the article, so that they would lose their place in the article, to their great frustration. They're almost ready to quit gemini entirely after this poor introductory experience :(

I hope that this is not a corner case related to our specific device and that you are able to find and resolve the issue! Please let me know if there is anything I can do to help.

**Comment by snoe** [comment]
@DocSunset I tried to reproduce this but I can't get the page to jump, are you on the latest version from 2022.0101 I believe this may have been an issue in the past?

Is this on android? Do you have a particular page this happens on?

**Comment by DocSunset** [comment]
This is on Android; the Play store reports that the app is up to date.

I tried to replicate this again this morning. I notice that the issue described doesn't seem to occur on the homepage at all. I suspect that the issue will only appear on very long pages with a lot of scrolling. I was able to recreate the issue on this page: gemini://beyondneolithic.life/graeber_archive/utopia_of_rules/dead_zones_of_the_imagination.gmi

**Comment by snoe** [comment]
I see, it looks like it's a bug in a third party library I was forced to use for text-selection. The further down the page, the further off selection occurs from where you tap. 

It seems flutter may support selecting across spans now, so it may be fixable by dropping the library.
