### ISSUE TITLE
Allow removal of homepage

### ISSUE THREAD

**Issue by licaon-kter** [snoe/deedum#63]
Home page url can't be blank, else the app fails to connect continuously.

Home page tab can't be closed.

Home page can't be stopped to connect at start.

Ref: https://forum.f-droid.org/t/tracking-anti-feature-for-deedum/17937

**Comment by snoe** [comment]
Thanks for the report!

**Comment by snoe** [comment]
Fixed by a7c6dd8

**Comment by licaon-kter** [comment]
Thanks
