### ISSUE TITLE
generating certificates?

### ISSUE THREAD

**Issue by crentava** [snoe/deedum#65]
hello, I need to use certificates on some gemini sites. Sorry if this has been covered, but I can’t find information about this anywhere. How do you generate certificates?

**Comment by snoe** [comment]
Client certificates are generated under "Identities". Create a new identity with a Name (you can leave the Certificate and Private Key blank and deedum will generate them, or you can paste in existing ones from other clients).

 Then go to your site and in the drop down menu, choose "Add to identity" and associate your cert with the site.

**Comment by crentava** [comment]
thank you so much! I didn’t know how this worked because I came from elaho on ios. Thanks for explaiining
